import type { Metadata } from "next";
import "./globals.css";
import Menu from "../components/menu";
import { TaskProvider } from "@/context/task-context";
import { Provider } from "./provider";
import { SnackbarProvider } from "@/context/snackbar-context";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Provider>
            <TaskProvider>
              <SnackbarProvider>
                <div className="flex h-screen justify-center overflow-y-auto bg-background py-5">
                  <div className="flex w-1/2 flex-col gap-4">
                    <Menu />
                    {children}
                  </div>
                </div>
              </SnackbarProvider>
            </TaskProvider>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
