import type { Metadata } from "next";
import "./globals.css";
import Menu from "../components/menu";
import { TaskProvider } from "@/context/task-context";
import { Provider } from "./provider";
import { UserProvider } from "@/context/user-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <UserProvider>
            <TaskProvider>
              <div className="flex h-screen justify-center overflow-y-auto bg-background py-5">
                <div className="flex w-1/2 flex-col gap-4">
                  <Menu />
                  {children}
                </div>
              </div>
            </TaskProvider>
          </UserProvider>
        </Provider>
      </body>
    </html>
  );
}
